# ~/routing.yml

include_homepage:
    module:
        name:           Homepage
        pattern:        /admin
        routing:        routing.yml

include_news:
    module:
        name:           News
        pattern:        /admin/news
        routing:        routing.yml