# ~/routing.yml

include_homepage:
    module:
        name:           Homepage
        pattern:        /
        routing:        routing.yml

include_news:
    module:
        name:           News
        pattern:        /news
        routing:        routing.yml