# ~/config/routing.yml
include:
    module:
        name:           Homepage
        pattern:        /
        routing:        routing.yml
    module:
        name:           News
        pattern:        /news
        routing:        routing.yml